export const datosVideos = [
    {
      id: 1,
      category: "music",
      creador: "AlexCG Design",
      logo: "https://th.bing.com/th/id/R.8a3abdf1460b77d1c398533821c279f3?rik=YZmlsOdw7XJuNw&pid=ImgRaw&r=0", //logo
      titulo: "🎧 💻 MÚSICA PARA PROGRAMADORES 📙 Música para programar , trabajar e inspirarte",
      visitas: "976.187 visualizaciones",
      fecha_subida: "18 ago 2018",
      duration: " 2:05:21",
      thumbnail: "https://th.bing.com/th/id/R.8a3abdf1460b77d1c398533821c279f3?rik=YZmlsOdw7XJuNw&pid=ImgRaw&r=0", //imagen de pantalla
      url: "https://www.youtube.com/embed/WWUoq4RtHV0",
    },
    {
      id: 2,
      category: "music",
      creador: "music for life",
      logo: "https://yt3.googleusercontent.com/Pjxm2y2DPbQUZ8xbyyXEsIlv1gfO4DjGtUxTG-IXIi9S-cb9nzaHtGIx_00KGePQoVSF6pJ3oQ=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Lofi Para Estudiar 📋 Sesión De Estudio [ Musica Para Concentrarse ] ",
      visitas: "16.202 visitas",
      fecha_subida: "6 jun 2022",
      duration: "1:00:03:44",
      thumbnail: "https://th.bing.com/th/id/R.bf538b7d3f433afc3c5ffb605fd8e694?rik=QAN9nX%2b7Gvf5lQ&pid=ImgRaw&r=0",
      url: "https://www.youtube.com/embed/GbVhuqUxFmE",
    },
    {
      id: 3,
      category: "music",
      creador: "TikTok Music",
      logo: "https://yt3.googleusercontent.com/UUJ6nmBDyYYkwsV2qXu6Ow5Ee-k1UlWQ9vzcVmAMQBMchPWYFOkFWbxVtU7KTWEtUHbJ0Jf8=s176-c-k-c0x00ffffff-no-rj",
      titulo: "KAROL G, Shakira - TQG (Letra + Video Oficial )",
      visitas: "4.957.711 visualizaciones ",
      fecha_subida: " 24 feb 2023",
      duration: "3:36",
      thumbnail: "https://th.bing.com/th/id/OIP.iT5zSXQkbVnkAVAX2oQMoQHaEK?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/I-LxPrZD-Ss",
    },
    {
      id: 4,
      category: "vlog",
      creador: "Explicame",
      logo: "https://yt3.googleusercontent.com/ytc/AL5GRJWwzMsD8Wv3zksnzsjXdTt0tgRfM6FzOfFZJBpw=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Qué es el Islam?",
      visitas: "192.461 visualizaciones",
      fecha_subida: " 8 dic 2021 ",
      duration: " 23:16",
      thumbnail: "https://th.bing.com/th/id/OIP.WyxmV5J4KknEgkJcbi1B3QHaEz?w=272&h=180&c=7&r=0&o=5&pid=1.7",
      url: "https://www.youtube.com/embed/9jkmx3QSCKI",
    },
    {
      id: 5,
      category: "music",
      creador: "El Cálamo",
      logo: "https://yt3.googleusercontent.com/SLWugVS-LptlaBS5-9FMFK2n86kQNmpKoa5GznI47Fcx2pWDS_ElCDkenuAf5vQaAH_KfidWPA=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Sura Al Fatiha - Sagrado Corán",
      visitas: "250.855 visualizaciones",
      fecha_subida: "29 sept 2015",
      duration: "0:54",
      thumbnail: "https://th.bing.com/th/id/R.cd050d2f03fea631624930ab4cb8836c?rik=1EU33ikgZp%2fR9g&pid=ImgRaw&r=0",
      url: "https://www.youtube.com/embed/hXgbcdWiTqo",
    },
    {
      id: 6,
      category: "vlog",
      creador: "CanalGalaxia 7",
      logo: "https://yt3.googleusercontent.com/ytc/AL5GRJUN6wRiqDSWgvdlTrPQb-x5oXkF_Oq9o8pvhwK1hg=s176-c-k-c0x00ffffff-no-rj",
      titulo: "La Historia del Islam - Documental completo",
      visitas: "77.804 visualizaciones  ",
      fecha_subida: "22 may 2020",
      duration: "48:35",
      thumbnail: "https://th.bing.com/th/id/R.b7e1fbb4fc9c910e31521c8b7292a1c5?rik=MAZmHPsNWnBKKQ&pid=ImgRaw&r=0",
      url: "https://www.youtube.com/embed/pOWp0fLt_S0",
    },
  
    {
      id: 7,
      category: "vlog",
      creador: "Guido Fernando Becerra",
      logo: "https://yt3.googleusercontent.com/ytc/AL5GRJVP949MMYxyAbotL6XSiUxxFzbrwcldcWe7Fw=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Isla Margarita lo tiene todo!",
      visitas: "149.721 visualizaciones  ",
      fecha_subida: "15 abr 2018",
      duration: "12:55",
      thumbnail: "https://th.bing.com/th/id/R.bfa8e952420ce2a0d98e421cdf02b364?rik=rkSydeY46cIiDA&riu=http%3a%2f%2fmundotravel360.com%2fwp-content%2fuploads%2f2018%2f01%2fmargarita-island-188868_1920.jpg&ehk=x944iqUff32meOWqmLMKGj6ZMSUQepKU05mibrruKqs%3d&risl=&pid=ImgRaw&r=0",
      url: "https://www.youtube.com/embed/O_sz0GcExgs",
    },
    {
      id: 8,
      category: "vlog",
      creador: "HolaMundo",
      logo: "https://yt3.googleusercontent.com/Z69fhRL9_OaXsDz-XsCUe2sGIqU7G1F5Mwl0PwlBsx_ll13K0nLb47q7_RMen7NHvzMVDgd2=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Aprende a programar ahora! - curso de introducción a la programación desde CERO",
      visitas: "285.943 visualizaciones ",
      fecha_subida: " 30 sept 2022",
      duration: "26:39",
      thumbnail: "https://th.bing.com/th/id/OIP.EcvSJrsafLQ8WPaLdaVSWgHaHa?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/VxrIZGQfxmE",
    },
  
    {
      id: 9,
      category: "vlog",
      creador: "Aprendiz Financiero",
      logo: "https://yt3.googleusercontent.com/ytc/AL5GRJX0w07b3SBgfKwlWMbg7_tDvoiN8vPIhNNbQe1UOA=s176-c-k-c0x00ffffff-no-rj",
      titulo: "La gente que usa estos 4 Trucos NO procrastina",
      visitas: "826.202 visualizaciones ",
      fecha_subida: " 20 nov 2022",
      duration: "7:14",
      thumbnail: "https://th.bing.com/th/id/OIP.g07-fs6vvOY2lgzbW5ncDwHaEs?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/CPHYtnoF1AQ",
    },
  
    {
      id: 10,
      category: "web",
      creador: "Soy Dalto",
      logo: "https://yt3.googleusercontent.com/jHpWdf9qWNdrCjxfQxCxR0aiYY9Y1IO7s6Jwlk-OgKxS8nzjEMffakE6mdOdp2u22R3130U0nQ=s176-c-k-c0x00ffffff-no-rj",
      titulo: "ANTES DE SUBIR UN SITIO WEB A INTERNET, MIRÁ ESTE VIDEO",
      visitas: "177.311 visualizaciones  ",
      fecha_subida: "18 abr 2021",
      duration: "11:34",
      thumbnail: "https://th.bing.com/th/id/OIP.EXcGKnztL9WfclinNZwY4gHaEJ?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/kltg9w3TiLc",
    },
  
    {
      id: 11,
      category: "web",
      creador: "AlexCG Design",
      logo: "https://th.bing.com/th/id/OIP.WI4XxnLZstO-myzgk-u7BAHaDU?pid=ImgDet&rs=1",
      titulo:"🎁 SUBIR pagina web a INTERNET GRATIS | HOSTING GRATUITO",
      visitas: "136.463 visualizaciones ",
      fecha_subida: " 9 mar 2020 ",
      duration: "12:36",
      thumbnail: "https://www.redeszone.net/app/uploads/2019/05/WebFreeHosting.jpg",
      url: "https://www.youtube.com/embed/un5WjcP027Q",
    },
    {
      id: 12,
      category: "web",
      creador: "deivchoi",
      logo: "https://yt3.googleusercontent.com/_8PV4sNd9CNRjFBH0Jts2oIMAGwPhKXPTZr9Ngr8awu104-NZJbupzUhPm3cXTF1ALTOW5az=s176-c-k-c0x00ffffff-no-rj",
      titulo:"Curso Básico de HTML5 y CSS3 Desde Cero",
      visitas: "397.640 visualizaciones  ",
      fecha_subida: "27 sept 2021",
      duration: " 36:36",
      thumbnail: "https://th.bing.com/th/id/OIP.YJd4lIhpVw_YKNuo6qKqNwHaEK?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/Y-OhzQpsRwI",
    },
    {
      id: 13,
      category: "web",
      creador: "deivchoi",
      logo: "https://yt3.googleusercontent.com/_8PV4sNd9CNRjFBH0Jts2oIMAGwPhKXPTZr9Ngr8awu104-NZJbupzUhPm3cXTF1ALTOW5az=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Curso Básico de HTML5 y CSS3 Desde Cero",
      visitas: "397.640 visualizaciones",
      fecha_subida: "27 sept 2021",
      duration: "36:36",
      thumbnail: "https://th.bing.com/th/id/OIP.YJd4lIhpVw_YKNuo6qKqNwHaEK?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/Y-OhzQpsRwI",
    },
    
    {
      id: 14,
      category: "music",
      creador: "AlexCG Design",
      logo: "https://th.bing.com/th/id/R.8a3abdf1460b77d1c398533821c279f3?rik=YZmlsOdw7XJuNw&pid=ImgRaw&r=0", //logo
      titulo: "🎧 💻 MÚSICA PARA PROGRAMADORES 📙 Música para programar , trabajar e inspirarte",
      visitas: "976.187 visualizaciones",
      fecha_subida: "18 ago 2018",
      duration: " 2:05:21",
      thumbnail: "https://th.bing.com/th/id/R.8a3abdf1460b77d1c398533821c279f3?rik=YZmlsOdw7XJuNw&pid=ImgRaw&r=0", //imagen de pantalla
      url: "https://www.youtube.com/embed/WWUoq4RtHV0",
    },

    {
      id: 15,
      category: "vlog",
      creador: "Explicame",
      logo: "https://yt3.googleusercontent.com/ytc/AL5GRJWwzMsD8Wv3zksnzsjXdTt0tgRfM6FzOfFZJBpw=s176-c-k-c0x00ffffff-no-rj",
      titulo: "Qué es el Islam?",
      visitas: "192.461 visualizaciones",
      fecha_subida: " 8 dic 2021 ",
      duration: " 23:16",
      thumbnail: "https://th.bing.com/th/id/OIP.WyxmV5J4KknEgkJcbi1B3QHaEz?w=272&h=180&c=7&r=0&o=5&pid=1.7",
      url: "https://www.youtube.com/embed/9jkmx3QSCKI",
    },

    {
      id: 16,
      category: "web",
      creador: "Soy Dalto",
      logo: "https://yt3.googleusercontent.com/jHpWdf9qWNdrCjxfQxCxR0aiYY9Y1IO7s6Jwlk-OgKxS8nzjEMffakE6mdOdp2u22R3130U0nQ=s176-c-k-c0x00ffffff-no-rj",
      titulo: "ANTES DE SUBIR UN SITIO WEB A INTERNET, MIRÁ ESTE VIDEO",
      visitas: "177.311 visualizaciones  ",
      fecha_subida: "18 abr 2021",
      duration: "11:34",
      thumbnail: "https://th.bing.com/th/id/OIP.EXcGKnztL9WfclinNZwY4gHaEJ?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/kltg9w3TiLc",
    },


    
    {
      id: 17,
      category: "vlog",
      creador: "RobertoRANDOM",
      logo: "https://yt3.googleusercontent.com/FxRcvHddboDS8MEs6o5GjMBijCSOJ2Dah1uVTS5-nWbjLntXTSbc2fldwz2hBz5j7nFdgqa7=s176-c-k-c0x00ffffff-no-rj",
      titulo: " Bart desmiente mitos Los simpsons capitulos completos en español latino",
      visitas: "32.798 visualizaciones ",
      fecha_subida: " 21 mar 2023",
      duration: "24:55",
      thumbnail: "https://th.bing.com/th/id/OIP.BgMk0NUkRH68c35ZyYHAzgAAAA?pid=ImgDet&rs=1",
      url: "https://www.youtube.com/embed/XAIuM71WwfA",
    },
  
    {
      id: 18,
      category: "vlog",
      creador: "Dr.Ahmad Abdo",
      logo: "https://yt3.googleusercontent.com/Jfty4fENxOT3cAw68AQ2L60anrczNgeC4TmSnl0IZTAuSkTOVPZqqkyXL-jneDBiIiREpoGCgQ=s176-c-k-c0x00ffffff-no-rj",
      titulo:"APRENDE CÓMO HACER LAS ORACIONES DEL DHUJR, ASR E ISHAA AQUÍ ☝ - La oración islámica",
      visitas: "1M  visitas",
      fecha_subida: "11 meses",
      duration: "16:01",
      thumbnail: "https://th.bing.com/th/id/R.e4081d1825bdacc572daa9c814faac25?rik=NLfM%2fKQRXlA4nw&pid=ImgRaw&r=0",
      url: "https://www.youtube.com/embed/eHqF_IZi9zg",
    },
  ];